all: my_suite
my_suite:
	./run_suite my_suite

asap_7nm:
	./run_suite asap_7nm

simple:
	./run_suite simple

tau:
	./run_suite tau

test:
	./run_suite test

example:
	./run_suite example

clean:
	rm -rf verilog/*
