#!/bin/bash
# possible calls: run_suite [my_suite|tau|test]

source ../000_config/setup.sh $1


for bench in "${these_benches[@]}"
do
    parms=(${bench_set[$benchkey]})
    clock_name=${parms[1]}

	for scenario in "${these_scenarios[@]}"
	do
        synth_result="${logic_synth_dir}/${bench}.${scenario}/${bench}.v"
        final_verilog="${bench}.v"

        echo "Input : ${synth_result}"
        echo "Output: verilog/${bench}.${scenario}/${final_verilog}"
        echo "--------------------------------------------------------------------------------"
        cmd="python3 ../utils/verilog_parser.py -i ${synth_result}"
        cmd="$cmd -o ${final_verilog} --clock_port $clock_name"
        cmd="$cmd --latch ${dff[0]} --latch_in ${dff[1]} --latch_out ${dff[2]} --latch_ck ${dff[3]}"
        cmd="$cmd --tie_hi ${tie_hi[0]} --tie_hi_out ${tie_hi[1]}"
        cmd="$cmd --tie_lo ${tie_lo[0]} --tie_lo_out ${tie_lo[1]}"
        echo $cmd
        $cmd | tee ${bench}.log.txt

        out_dir="${final_verilog_dir}/${bench}.${scenario}"

        echo "" | tee --append ${bench}.log.txt
        echo "" | tee --append ${bench}.log.txt

        if [ -d $out_dir ]; then
            rm -rf $out_dir
        fi

        mkdir -p ${out_dir}
        mv ${final_verilog} ${out_dir}
        mv ${bench}.log.txt ${out_dir}
	done
done

